### Data Encoding

 1.Nominal/ OHE Encoding
 2.Label and ordinal Encoding
 3.Target Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [3]:

df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
encoder=OneHotEncoder()

In [5]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [7]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [8]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
lbl_encoder=LabelEncoder()

In [11]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\acer\Desktop\feat_eng\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [12]:
lbl_encoder.transform([['red']])

c:\Users\acer\Desktop\feat_eng\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [13]:
lbl_encoder.transform([['blue']])

c:\Users\acer\Desktop\feat_eng\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [14]:
lbl_encoder.transform([['green']])

c:\Users\acer\Desktop\feat_eng\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

## Ordinal Encoding

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [17]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])